name: Update versions

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest versions
        uses: nick-fields/retry@v4
        with:
          max_attempts: 5
          timeout_minutes: 10
          command: |
            set -uo pipefail
            POSTGRES=$(git ls-remote --tags https://github.com/postgres/postgres \
              | awk -F/ '/REL_[0-9]+_[0-9]+/ {gsub("REL_", ""); gsub("_", "."); print $3}' \
              | sort -V | uniq | tail -1)
            GCC=$(curl -sf https://ftp.gnu.org/gnu/gcc/ \
              | grep -o 'gcc-[0-9]\+\.[0-9]\+\.[0-9]\+/' \
              | sed 's#gcc-##; s#/##' \
              | sort -V | tail -n 1)          
            ZLIB=$(curl -sf https://zlib.net/ \
              | grep -o 'zlib-[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?\.tar\.gz' \
              | sed 's/zlib-//; s/\.tar\.gz//' \
              | sort -V | tail -n 1)
            OPENSSL=$(git ls-remote --tags https://github.com/openssl/openssl \
              | awk -F/ '/[0-9]$/  && /openssl-/ && ! /-[a-z]/ {gsub("openssl-", ""); print $3}' \
              | sort -V | grep -Ev '^4' | tail -1)
            ICU=$(git ls-remote --tags https://github.com/unicode-org/icu \
              | awk -F/ '/\/release/&& !/rc/ {gsub("release-", ""); print $3}' \
              | sort -V | tail -1)
            READLINE=$(curl -sf https://ftp.gnu.org/gnu/readline/ \
              | grep -Eo 'readline-[0-9]+(\.[0-9]+)*\.tar\.gz' \
              | sed -E 's/readline-([0-9.]+)\.tar\.gz/\1/' \
              | sort -uV | tail -1)
            NCURSES=$(curl -sf https://ftp.gnu.org/gnu/ncurses/ \
              | grep -Eo 'ncurses-[0-9]+(\.[0-9]+)*\.tar\.gz' \
              | sed -E 's/ncurses-([0-9.]+)\.tar\.gz/\1/' \
              | sort -uV | tail -1)
            POPEN_SHIM=$(git ls-remote --tags https://github.com/simons-containers/no-sh-popen-shim \
              | awk -F/ '/v[0-9]/ && !/\^\{\}$/ {gsub("v", ""); print $3}' \
              | sort -V | tail -1)
            LIBURING=$(git ls-remote --tags --refs https://github.com/axboe/liburing.git \
              | awk -F/ '! /rc[0-9]*/ {gsub("liburing-", "");  print $3 }' \
              | sort -uV | tail -1)
  
            : ${POSTGRES:?} ${GCC:?} ${ZLIB:?} ${OPENSSL:?} ${ICU:?} ${READLINE:?} ${NCURSES:?} ${POPEN_SHIM:?} ${LIBURING:?}
            yq -i ".postgres= \"$POSTGRES\"" versions.yaml
            yq -i ".gcc= \"$GCC\"" versions.yaml
            yq -i ".zlib= \"$ZLIB\"" versions.yaml
            yq -i ".openssl= \"$OPENSSL\"" versions.yaml
            yq -i ".icu= \"$ICU\"" versions.yaml
            yq -i ".readline= \"$READLINE\"" versions.yaml
            yq -i ".ncurses= \"$NCURSES\"" versions.yaml
            yq -i ".popen_shim= \"$POPEN_SHIM\"" versions.yaml
            yq -i ".liburing= \"$LIBURING\"" versions.yaml
            git diff versions.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update versions
          commit-message: Update versions
